
eureka:
  instance:
    hostname: localhost # 服务提供者应用所在的主机（本地测试的话，使用localhost或者127.0.0.1即可，或者在host文件中指定一个虚拟域名也可以）
    lease-renewal-interval-in-seconds: 5 # 心跳时间，表示eureka client发送心跳给eureka server端的频率（缺省为30s）
  client:
    service-url:
      defaultZone: http://server.eureka.slave1.com:18761/eureka,http://server.eureka.slave2.com:28761/eureka # 指定eureka服务器集群列表地址.
spring:
  application:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10
    password: password
    pool:
      # 连接池中的最大空闲连接
      max-idle: 500
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 1000
      #  最长等待时间
      max-wait: -1

    datasource:
      url: jdbc:mysql://localhost:3306/hotel?useUnicode=true&serverTimezone=Asia/Shanghai
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
        #----durid info ---
        type: com.alibaba.druid.pool.DruidDataSource
      #----addtion info --
    dbcp:
      max-active: 1000
      initial-size: 100
      min-idle: 500
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false